import {ProviderHelper} from 'myutil';

const TOKEN_TYPE_PAINT_NFT = 0;
const TOKEN_TYPE_CANVAS_PAINT_ETH_LP = 1;
const TOKEN_TYPE_CANVAS_NFT = 2;
const TOKEN_TYPE_PAINT_POOL = 3;

const NFT_CHAIN_NONE = -1;

const WEBTHREE_TIMEOUT_LIMIT_MS = 1000 * 60;
const BACKEND_TIMEOUT_LIMIT_MS = 1000 * 60 * 2;
const TRANSACTION_TIMEOUT_LIMIT_MS = 1000 * 60 * 2;

export {
    TOKEN_TYPE_PAINT_NFT, 
    TOKEN_TYPE_CANVAS_PAINT_ETH_LP, 
    TOKEN_TYPE_CANVAS_NFT, 
    TOKEN_TYPE_PAINT_POOL,
    NFT_CHAIN_NONE, 
    BACKEND_TIMEOUT_LIMIT_MS,
    WEBTHREE_TIMEOUT_LIMIT_MS,
    TRANSACTION_TIMEOUT_LIMIT_MS,
};

const ERR_WALLET_IS_NOT_CONNECTED = 'ERR_WALLET_IS_NOT_CONNECTED';
const ERR_LIMIT_LOCKUP_NFT = 'ERR_LIMIT_LOCKUP_NFT';
const ERR_UNSKAKING_INPROGRESS = 'ERR_UNSKAKING_INPROGRESS';
const ERR_UNSUPPORTED_TOKEN_TYPE = 'ERR_UNSUPPORTED_TOKEN_TYPE';
const ERR_UNSUPPORTED_CONTRACT_TYPE = 'ERR_UNSUPPORTED_CONTRACT_TYPE';
const ERR_BACKEND_RESPONSE = 'ERR_BACKEND_RESPONSE';
const ERR_RESPONSE_TIMEOUT = 'ERR_RESPONSE_TIMEOUT';
const ERR_INVALID_WEB3_NETWORK = 'ERR_INVALID_WEB3_NETWORK';
const ERR_REWARD_INPROGRESS = 'ERR_REWARD_INPROGRESS';
const ERR_REJECT_TRANSACTION = 4001
const ERR_BALANCE_EMPTY = 'ERR_BALANCE_EMPTY';
const ERR_AXIOS_TIMEOUT = "ECONNABORTED";

export {
    ERR_WALLET_IS_NOT_CONNECTED,
    ERR_LIMIT_LOCKUP_NFT,
    ERR_UNSKAKING_INPROGRESS,
    ERR_REWARD_INPROGRESS,

    ERR_UNSUPPORTED_TOKEN_TYPE,
    ERR_UNSUPPORTED_CONTRACT_TYPE,
    ERR_BACKEND_RESPONSE,

    ERR_RESPONSE_TIMEOUT,
    ERR_INVALID_WEB3_NETWORK,
    ERR_REJECT_TRANSACTION,
    ERR_BALANCE_EMPTY,

    ERR_AXIOS_TIMEOUT
};

const IDLE_OPEN_SALE = 'IDLE_OPEN_SALE';
const TRY_JOIN_OPEN_SALE = 'TRY_JOIN_OPEN_SALE';
const JOINED_OPEN_SALE = 'JOINED_OPEN_SALE';
const PURCHASED_OPEN_SALE = 'PURCHASED_OPEN_SALE';

export {
    IDLE_OPEN_SALE,
    TRY_JOIN_OPEN_SALE,
    JOINED_OPEN_SALE,
    PURCHASED_OPEN_SALE
};

const CONTRACT_TYPE_1155 = 1155;
const CONTRACT_TYPE_721 = 721;

export {
    CONTRACT_TYPE_1155,
    CONTRACT_TYPE_721
}